### ISSUE TITLE
Not working - cloned, npm install, npm start - showing "You are logged out." always

### ISSUE THREAD

**Issue by joedeveloper** [janikvonrotz/meteor-apollo-accounts-example#6]
Tried logging in with admin@example.com / password - as well as via google - no success

Not sure if related to the problem with logging in, but seeing this:

`
20170428-23:26:58.400(7)? Exception in setTimeout callback: Error: That user has no unverified email addresses.
I20170428-23:26:58.401(7)?     at AccountsServer.meteorInstall.node_modules.meteor.accounts-password.password_server.js.Accounts.sendVerificationEmail (packages/accounts-password/password_server.js:762:13)
I20170428-23:26:58.401(7)?     at server/account.js:29:16
I20170428-23:26:58.401(7)?     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
I20170428-23:26:58.402(7)?     at packages/meteor.js:445:45
I20170428-23:26:58.402(7)?     at runWithEnvironment (packages/meteor.js:1176:24)
`

**Comment by dmiepub** [comment]
Getting same message alway:
"You are logged out."
joedeveloper 
do you find any solution?
